---
driver:
  name: vagrant
  customize:
    cpus: 1
    memory: 1024


provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: kafka-1
    driver:
      network:
        - ["private_network", {ip: "192.168.17.201"}]
    run_list:
      recipe[kafka-cluster::kafka]
    attributes:
  - name: kafka-2
    driver:
      network:
        - ["private_network", {ip: "192.168.17.202"}]
    run_list:
      recipe[kafka-cluster::kafka]
    attributes:
  - name: kafka-3
    driver:
      network:
        - ["private_network", {ip: "192.168.17.203"}]
    run_list:
      recipe[kafka-cluster::kafka]
    attributes:
  - name: zookeeper-1
    driver:
      network:
        - ["private_network", {ip: "192.168.17.211"}]
    run_list:
      recipe[kafka-cluster::zookeeper]
    attributes:
  - name: zookeeper-2
    driver:
      network:
        - ["private_network", {ip: "192.168.17.212"}]
    run_list:
      recipe[kafka-cluster::zookeeper]
    attributes:
  - name: zookeeper-3
    driver:
      network:
        - ["private_network", {ip: "192.168.17.213"}]
    run_list:
      recipe[kafka-cluster::zookeeper]
    attributes: