name             'kafka-cluster'
maintainer       'Daniel Klopp'
maintainer_email 'see github'
license          'All rights reserved'
description      'Installs/Configures kafka-cluster'
long_description 'Installs/Configures kafka-cluster'
version          '0.1.0'

depends 'apt'
depends 'java'
depends 'kafka'